# Generated by Django 5.0 on 2023-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PAYMENT', 'Payment'), ('ACCEPTED', 'Accepted'), ('CANCELED', 'Canceled'), ('DELIVERED', 'Delivered')], default='INITIAL', max_length=255),
        ),
    ]
